apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  annotations:
    org/pkg: 'PuppetContent/PuppetContent_abn_amro_rpm'
spec:
  type: website
  owner: guests
  lifecycle: experimental
